# yamllint disable-file
---
name: Install tkn
runs:
  using: "composite"
  steps:
    - run: |
        # Get latest tkn CLI version
        TKN_CLI_VERSION=$(curl -s https://api.github.com/repos/tektoncd/cli/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
        echo "Installing tkn CLI version: $TKN_CLI_VERSION"
        curl -LO "https://github.com/tektoncd/cli/releases/download/v${TKN_CLI_VERSION}/tektoncd-cli-${TKN_CLI_VERSION}_Linux-64bit.deb"
        sudo dpkg -i ./tektoncd-cli-${TKN_CLI_VERSION}_Linux-64bit.deb
      shell: bash
