---
repos:
  - repo: local
    hooks:
      - id: check-vault-encrypted
        name: Check vault files are encrypted
        entry: scripts/check-vault-encrypted.sh
        language: script
        files: '.*vault.*\.(yaml|yml)$'
        pass_filenames: true
