---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: collect-push-rpm-params
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: push-koji
spec:
  params:
    - name: dataPath
      type: string
      description: |
        Path to the JSON file of the merged data to use in the data workspace.
  steps:
    - name: collect-push-rpm-params
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eux

        DATA_FILE="$(params.dataPath)"
        if [ ! -f "${DATA_FILE}" ] ; then
            echo "No data JSON was provided."
            exit 1
        fi

        # Put the .pushOptions.pushKeytab value into the result that can be used by another task
        jq -jr '.pushOptions.pushKeytab.secret' "$DATA_FILE" > '$(results.secret.path)'

        # Put the .pushOptions.pushPipelineImage value into the result that can be used on other task
        jq -jr '.pushOptions.pushPipelineImage' "$DATA_FILE" > '$(results.pipelineImage.path)'
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data
  results:
    - name: secret
      type: string
      description: |
        The string of the secrets to store the keytabs and oras login info
    - name: pipelineImage
      type: string
      description: |
        The pipeline image that is used for push builds into Koji instance
