---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${tenant_collector_sa_name}
secrets:
  - name: jira-collectors-secret-${component_name}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${tenant_sa_name}
