---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: filter-already-released-advisory-images-task
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |
    Filters out images from a snapshot if they are already published in an advisory
    stored in the GitLab advisory repo. Returns a list of component names
    that still need to be released (i.e., not found in any advisory).
  params:
    - name: transformedSnapshot
      type: string
      description: Base64 string of gzipped JSON representation of architecture-specific images from snapshot
    - name: origin
      description: The origin workspace for the release CR
      type: string
    - name: advisory_secret_name
      description: Name of the secret containing advisory metadata
      type: string
    - name: internalRequestPipelineRunName
      description: Name of the PipelineRun that requested this task
      type: string
  results:
    - name: result
      description: Success or error message
    - name: internalRequestPipelineRunName
      description: The name of the InternalRequest PipelineRun
    - name: internalRequestTaskRunName
      description: The name of the InternalRequest TaskRun
    - name: unreleased_components
      description: List of components that still need to be released encoded as a gzipped base64 string
  steps:
    - name: filter-images
      image: quay.io/konflux-ci/release-service-utils:0b2f257d7a5c2a881c36c23f8ae3cd5e89db593a
      computeResources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
          cpu: 500m
      env:
        - name: GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: $(params.advisory_secret_name)
              key: gitlab_host
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.advisory_secret_name)
              key: gitlab_access_token
        - name: GIT_REPO
          valueFrom:
            secretKeyRef:
              name: $(params.advisory_secret_name)
              key: git_repo
        - name: GIT_AUTHOR_NAME
          valueFrom:
            secretKeyRef:
              name: $(params.advisory_secret_name)
              key: git_author_name
        - name: GIT_AUTHOR_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.advisory_secret_name)
              key: git_author_email
        - name: TRANSFORMED_SNAPSHOT
          value: "$(params.transformedSnapshot)"
      script: |
        #!/usr/bin/env bash
        set -eo pipefail

        STDERR_FILE=/tmp/stderr.txt
        echo -n "$(params.internalRequestPipelineRunName)" > "$(results.internalRequestPipelineRunName.path)"
        echo -n "$(context.taskRun.name)" > "$(results.internalRequestTaskRunName.path)"

        exitfunc() {
          local err=$1
          local line=$2
          local cmd=$3
          if [ "$err" -eq 0 ]; then
            echo -n "Success" > "$(results.result.path)"
          else
            echo -n "$0: ERROR '$cmd' failed at line $line - exited with status $err" > "$(results.result.path)"
            if [ -f "$STDERR_FILE" ]; then tail -n 20 "$STDERR_FILE" >> "$(results.result.path)"; fi
          fi
          exit 0
        }
        trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT

        TRANSFORMED_SNAPSHOT_JSON=$(base64 -d <<< "$TRANSFORMED_SNAPSHOT" | gunzip)

        echo "Transformed Snapshot JSON (arch-specific): $TRANSFORMED_SNAPSHOT_JSON"

        ORIGIN="$(params.origin)"
        ADVISORY_BASE_DIR="data/advisories/${ORIGIN}"

        cd /tmp

        echo "Cloning $GIT_REPO..."
        # Use sparse checkout to only get the advisory directory
        git clone --depth=1 --filter=blob:none --no-checkout "$GIT_REPO" repo
        cd repo
        git sparse-checkout set "$ADVISORY_BASE_DIR"
        git checkout

        echo "Checking existing advisories in ${ADVISORY_BASE_DIR}..."
        EXISTING_ADVISORIES=""
        if [ -d "${ADVISORY_BASE_DIR}" ]; then
          EXISTING_ADVISORIES=$(
            find "${ADVISORY_BASE_DIR}" -mindepth 2 -type d -printf "%T@ %p\n" |
            sort -nr | cut -d' ' -f2- | sed "s|^${ADVISORY_BASE_DIR}/||"
          )
        fi

        if [[ -z "$EXISTING_ADVISORIES" ]]; then
          echo "No existing advisories found. No components have been released yet."
          # Extract unique original component names from transformed snapshot
          UNRELEASED_COMPONENTS=$(echo "$TRANSFORMED_SNAPSHOT_JSON" \
            | jq -c '[.[].originalComponent] | unique' \
            | gzip -c \
            | base64 -w 0)
          echo -n "$UNRELEASED_COMPONENTS" > "$(results.unreleased_components.path)"
          echo -n "Success" > "$(results.result.path)"
          exit 0
        fi

        EXISTING_CONTENT=/tmp/existing_content.json
        # Use a mutable working set for progressive filtering across advisories
        ARCH_IMAGES="$TRANSFORMED_SNAPSHOT_JSON"
        for ADVISORY_SUBDIR in $EXISTING_ADVISORIES; do
          ADVISORY_FILE="${ADVISORY_BASE_DIR}/${ADVISORY_SUBDIR}/advisory.yaml"
          yq -o=json '.spec.content.images // []' "$ADVISORY_FILE" > "$EXISTING_CONTENT"

          echo "Comparing against: $ADVISORY_FILE"

          # Filter arch-specific images using original triple-match logic
          ARCH_IMAGES=$(echo "$ARCH_IMAGES" | jq --slurpfile existing "$EXISTING_CONTENT" '
            map(select(
              .containerImage as $ci |
              .tags as $tags |
              .repository as $repo |
              ($existing[0] | map(select(
                .containerImage == $ci and .tags == $tags and .repository == $repo
              )) | length == 0)
            ))')

          # If no arch images remain, all components are released
          if jq -e 'length == 0' <<< "$ARCH_IMAGES" >/dev/null; then
            echo "All arch images in the snapshot have already been released in advisories. Stopping pipeline."
            echo -n "[]" | gzip -c | base64 -w 0 > "$(results.unreleased_components.path)"
            echo -n "Success" > "$(results.result.path)"
            exit 0
          fi
        done

        # Extract unique original component names from remaining arch images (Martin's approach)
        ORIGINAL_ARCH_COUNT=$(echo "$TRANSFORMED_SNAPSHOT_JSON" | jq 'length')
        REMAINING_ARCH_COUNT=$(echo "$ARCH_IMAGES" | jq 'length')
        echo "Filtered out $((ORIGINAL_ARCH_COUNT - REMAINING_ARCH_COUNT)) arch-specific image(s) already in advisories"
        echo "Remaining unpublished arch images: $ARCH_IMAGES"

        # Map back to original components and get unique names (Martin's approach)
        UNRELEASED_COMPONENTS=$(echo "$ARCH_IMAGES" | jq -c '[.[].originalComponent] | unique' | gzip -c | base64 -w 0)
        echo -n "$UNRELEASED_COMPONENTS" > "$(results.unreleased_components.path)"
        echo -n "Success" > "$(results.result.path)"
