---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: update-fbc-catalog
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: fbc
spec:
  description: |-
    Tekton pipeline add/update FBC fragments to the FBC catalog by interacting with IIB service for File Based Catalogs
  params:
    - name: iibServiceAccountSecret
      type: string
      description: Secret containing the credentials for IIB service
      default: iib-service-account
    - name: publishingCredentials
      type: string
      description: Secret containing the publishing credentials used to fetch the image config
    - name: fbcFragments
      type: string
      description: FBC fragments built by Konflux as JSON array (e.g. ["fragment1", "fragment2"])
    - name: fromIndex
      type: string
      description: >-
        Index image (catalog of catalogs) the FBC fragment will be added to
    - name: buildTags
      type: string
      default: '[]'
      description: >-
        List of additional tags the internal index image copy should be
        tagged with
    - name: addArches
      type: string
      default: '[]'
      description: List of arches the index image should be built for
    - name: mustPublishIndexImage
      type: string
      default: "false"
      description: Whether the index image should be published (pre-determined by prepare-fbc-parameters)
    - name: mustOverwriteFromIndexImage
      type: string
      default: "false"
      description: Whether to overwrite the from index image (pre-determined by prepare-fbc-parameters)
    - name: buildTimeoutSeconds
      type: string
      default: "3600"
      description: Timeout seconds to receive the build state
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  tasks:
    - name: update-fbc-catalog-task
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/update-fbc-catalog-task/update-fbc-catalog-task.yaml
      params:
        - name: iibServiceAccountSecret
          value: $(params.iibServiceAccountSecret)
        - name: publishingCredentials
          value: $(params.publishingCredentials)
        - name: fbcFragments
          value: $(params.fbcFragments)
        - name: fromIndex
          value: $(params.fromIndex)
        - name: buildTags
          value: $(params.buildTags)
        - name: addArches
          value: $(params.addArches)
        - name: mustPublishIndexImage
          value: $(params.mustPublishIndexImage)
        - name: mustOverwriteFromIndexImage
          value: $(params.mustOverwriteFromIndexImage)
        - name: buildTimeoutSeconds
          value: $(params.buildTimeoutSeconds)
  results:
    - name: jsonBuildInfo
      value: $(tasks.update-fbc-catalog-task.results.jsonBuildInfo)
    - name: buildState
      value: $(tasks.update-fbc-catalog-task.results.buildState)
    - name: indexImageDigests
      value: $(tasks.update-fbc-catalog-task.results.indexImageDigests)
    - name: iibLog
      value: $(tasks.update-fbc-catalog-task.results.iibLog)
    - name: exitCode
      value: $(tasks.update-fbc-catalog-task.results.exitCode)
