---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: check-fbc-opt-in
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Internal pipeline to check FBC opt-in status for container images via Pyxis.
    Uses the simplified check-fbc-opt-in task to query Pyxis for each provided container image.
  params:
    - name: containerImages
      description: JSON array of container images to check for FBC opt-in status
      type: string
    - name: pyxisSecret
      description: Name of secret which contains the required credentials for authentication to pyxis
      type: string
    - name: pyxisServer
      description: Pyxis server to use
      type: string
      default: production
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  results:
    - name: optInResults
      type: string
      value: $(tasks.check-fbc-opt-in.results.optInResults)
      description: JSON array containing opt-in status for each container image
  tasks:
    - name: check-fbc-opt-in
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/check-fbc-opt-in/check-fbc-opt-in.yaml
      params:
        - name: containerImages
          value: $(params.containerImages)
        - name: pyxisSecret
          value: $(params.pyxisSecret)
        - name: pyxisServer
          value: $(params.pyxisServer)